bot:
  bot_token: "MTA4MTg1Nzc5OTc5NDk4NzA0OQ.GY1gHU.Zr8kWU4WXIN_Yx2JAjr3M3J2NBjVw8XkO4noC8"
  discord_char_limit: 2000
  discord_dropdown_limit: 25
  admin_users:
    - 257785837813497856 
    - 209382762971398144
    - 300930955579752448
    - 191561233755799554
  presence:
    update_interval_sec: 3
  chat:
    update_interval_sec: 5
    duration_min: 900
    lines: 10

minecraft:
  service_name: "phoenix.service"
  service_path: "/etc/systemd/system"
  server_path: "/mnt/SSD120GB/phonix/PhoenixDenPack2025"
  backup:
    enabled: true
    interval_min: 15
    path: "/var/mcbackup/"
  modpack_url: "https://www.curseforge.com/minecraft/modpacks/the-phoenix-den-pack"
  restart:
    enabled: true
    times:
      - "12:00"
      - "00:00"

stats:
  csv_interval_min: 5
  csv_path: "_data/stats.csv"
  player_count_png: "_data/stat_players.png"
