bot:
  sync_commands: False  # Whether to sync commands with Discord on startup
  bot_token: ""  # Discord bot token (keep this secret)
  discord_char_limit: 2000  # Maximum message length allowed in Discord
  discord_dropdown_limit: 25  # Maximum options in dropdown menus
  admin_users: # List of Discord user IDs with admin permissions
    - 123123123123123123  # Ola Nordmann
  admin_roles:  # List of Discord role IDs with admin permissions
    - 123456789045678907 # "Minecraft Admin" role  presence:
  update_interval_sec: 3  # How often to update bot presence (in seconds)
  chat:
    update_interval_sec: 5  # How often to check for new chat messages
    duration_min: 900  # How long chat messages are kept before being removed (in minutes)
    lines: 10  # Number of chat lines displayed when fetching logs

minecraft:
  server_path: "/usr/share/minecraft"  # Path to the Minecraft server directory
  backup:
    enabled: true  # Whether automatic backups are enabled
    path: "/var/mcbackup/"  # Directory where backups are stored
    interval_min: 15  # How often to create backups (in minutes)
    delete_frequent_after_hours: 24  # Delete frequent backups after this many hours
    delete_sparse_after_days: 120  # Delete older, less frequent backups after this many days
  modpack_url: "https://www.curseforge.com/minecraft/modpacks/the-phoenix-den-pack"  # Link to the modpack download
  restart:
    enabled: true  # Whether scheduled restarts are enabled
    cold_backup_on_restart: True  # Create a full backup before restarting, ensuring no changes to the backup while we're copying it.
    times:
      - "12:00"  # Scheduled restart time (24-hour format)
      - "00:00"  # These can be added dynamically using the "/restart add" command. 
  service_name: ""  # Systemd service name (auto-populated if left empty)
  service_path: "/etc/systemd/system"  # Path to systemd service files

curseforge:
  api_key: ""
  base_url: https://api.curseforge.com

notifications:
  errors_enabled: True # Whether to send notifications for MC errors
  check_last_min: 1 # How often in minutes to check for errors in the minecraft log
  threshold_sec: 10 # if there has been 10sec of lag in th last 10min, send a notification and mute for 30min
  lag_window_min: 10 # How far back search the MC logs for lag in minutes
  notification_cooldown_min: 30 # After sending a notification, wait this long before sending another of the same type.
  generic_error_patterns: # Dictionary of MC log error patterns and their corresponding explanations .
    "Failed to store chunk": "The server couldn't save a chunk properly. This might indicate disk issues or corrupted data.\nConsider investigating the chunk and do a `/backup restore` if it was important."
    "Forcing regeneration of chunk": "The server is regenerating a chunk due to corruption or missing data.\nConsider investigating the chunk and do a `/backup restore` if it was important."
    "Rebuilding corrupted chunk": "A chunk was detected as corrupted and is being rebuilt.\nConsider investigating the chunk and do a `/backup restore` if it was important."
    "Missing chunk": "A requested chunk was missing. This could lead to visual glitches or desync."
    "stream is truncated: expected": "A chunk's data appears incomplete. This might indicate file corruption or interrupted saving.\nConsider investigating the chunk and do a `/backup restore` if it is reset or broken."


stats:
  csv_interval_min: 5  # How often to log player stats (in minutes)
  csv_path: "_data/stats.csv"  # Path to the CSV file storing stats
  player_count_png: "_data/stat_players.png"  # Path to the player count graph image
  lag_png: "_data/stat_lag.png"  # Path to the lag graph image