bot:
  bot_token: ""
  discord_char_limit: 2000
  discord_dropdown_limit: 25
  admin_users:
    - 123123123123123123 
  presence:
    update_interval_sec: 3
  chat:
    update_interval_sec: 5
    duration_min: 900
    lines: 10

minecraft:
  service_name: "minecraft.service"
  service_path: "/etc/systemd/system"
  server_path: "/usr/share/minecraft"
  backup:
    enabled: true
    interval_min: 15
    path: "/var/mcbackup/"
    delete_frequent_after_hours: 24
    delete_sparse_after_days: 120
  modpack_url: "https://www.curseforge.com/minecraft/modpacks/the-phoenix-den-pack"
  restart:
    enabled: true
    cold_backup_on_restart: True
    times:
      - "12:00"
      - "00:00"

stats:
  csv_interval_min: 5
  csv_path: "_data/stats.csv"
  player_count_png: "_data/stat_players.png"
